version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017//ocu-challenge
    ports:
      - '7070:7070'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/node-app
    networks:
      - app-network

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
